### ISSUE TITLE
The user should be displayed a sensible error message instead of the "postgres tx error" toast message

### ISSUE THREAD

**Issue by jschummer** [HSLdevcom/jore4#893] opened 2022-07-13 11:18 UTC
It is not always feasible to have the frontend perform all checks on whether a specific user action is allowed in a certain context. A simple solution would be to allow the user perform the action and catch the backend "postgres tx error" and display the user a generic error message instead.

The most important case is the route verification constraint, which checks whether a journey pattern with all scheduled stop points is compatible with its route. This check is difficult to perform in the frontend and it is cumbersome to provide check functions for all different scenarios that can trigger the check (adding a stop instance, including a label into a journey pattern, deleting a route / journey pattern, etc).

For these cases, it would be an easy solution to let the user attempt the action. In case it fails because of said constraint, the user could be displayed a generic error, e.g. "Could not perform the attempted action. Please check the compatibility of the routes and stop points included in the action" or similar.

This could be realized by parsing the error message received from the backend. Either directly, or a Hasura action could be used to generate a custom http response code, which is then caught.

**Comment by tk-vincit** [comment] 2022-08-11 07:19
Duplicate of https://github.com/HSLdevcom/jore4/issues/739

**Closed by tk-vincit** 2022-08-11 07:19 UTC
Labels: frontend, Routes and lines, estimate-M

**Comment by sr-vala** [comment] 2022-09-16 10:42
Moved to done since this was marked as a duplicate and there should be no further actions.
