### ISSUE TITLE
Research "pysäkki poistetaan seuraavilta reiteiltä"

### ISSUE THREAD

**Issue by eleksi** [HSLdevcom/jore4#1251] opened 2023-04-28 07:01 UTC
For some reason adding Hastus place to So3098 stop (in production dump) will show the following message.

![Image](https://user-images.githubusercontent.com/51695324/235077579-e2326df7-ff32-4b0a-ae49-bd8a8f166c73.png)

It is possible that the message is just wrong, and it is there just in case the stop would be moved to other infrastructure link. Regardless, it is a bit weird user sees a message like that when we are just adding a Hastus place.

**Comment by HenrikHartiala** [comment] 2023-05-04 07:33
We should first check that what actually happens after the change is confirmed. Does this actually remove the stop from the routes? If so, we need to check why that happens. Does some function think that we changed the location of the stop? Adding hastus place should not affect routes in the manner of removing the stop from routes.

**Comment by sr-vala** [comment] 2023-05-08 09:24
Possibly related: #1017

**Comment by HenrikHartiala** [comment] 2023-08-31 08:28
UPDATE 31.8.2023:
It seems that this has nothing to do with Hastus place, and more so with some location / direction mismatches. You can reproduce this as well with the dump data by navigating to a route (e.g. 195) -> go to the map via the route row -> open So3098 -> edit -> save (no changes).
The location etc. has some mismatch and saving this will actually change the direction of the stop and that is what obviously causes the removal of the stop from the routes that uses this stop.

**Comment by HenrikHartiala** [comment] 2023-09-04 10:48
Closing this ticket since the bug is not actually related to hastus places and the reasearch is done. New ticket on this matter is here: https://github.com/HSLdevcom/jore4/issues/1433

**Closed by HenrikHartiala** 2023-09-04 10:48 UTC
Labels: frontend, Timetables
