### ISSUE TITLE
Fix map modal position after page scroll

### ISSUE THREAD

**Issue by eleksi** [HSLdevcom/jore4#661] opened 2022-03-03 09:26 UTC
After scrolling the page down and then opening the map modal (by for example clicking a location marker), the map modal modal opens to the top of the page (not to the top of browser view) and is partially invisible.

![screenshot](https://user-images.githubusercontent.com/51695324/156535893-04cca992-85f8-43d7-a212-d80af90f84c2.png)

**Comment by pkainulainen-vincit** [comment] 2022-03-30 10:06
This seems to be a bug of @headlessui/react When I updated the @headlessui/react to the version 1.5.0, I could no longer reproduce this issue. Because @headlessui/react will be updated after this PR: https://github.com/HSLdevcom/jore4-ui/pull/127 is merged to master, I will simply close this issue.

**Note that if you are using Firefox**, a small portion of the original page is shown on the bottom of the screen when the map model is visible. However, because this's most likely a bug of @headlessui/react, it might be best to wait until it's fixed by the @headlessui/react team.

**Closed** 2022-04-14 11:10 UTC
Labels: bug, good first issue, frontend, Routes and lines, estimate-S
