### ISSUE TITLE
As a Developer I want that the most fitting map library is used on the user interface

### ISSUE THREAD

**Issue by pallost** [HSLdevcom/jore4#318] opened 2021-05-05 06:27 UTC
...should research React map libraries and find the most fitting one that supports most of the desired features. Let's collect here what features we would like to (possibly) use and the results of our research that which libraries support these the best

**Comment by pallost** [comment] 2021-05-05 06:30
Must have: simple zoom in-out, for easy navigation
Must have: simple panning, for easy navigation
Must have: simple way of creating nodes, for creating bus stops and other POI
Must have: simple way of creating edges, for drawing routes and roads between nodes

**Comment by pallost** [comment] 2021-05-05 06:33
Could have: simple way of selecting multiple edges and nodes in an area, for batch editing attributes for each or for selecting parts of a network that is imported from a source
Should have: while drawing, dragging or dropping, snapping nodes and edges to and underlying infrastructure network grid

**Comment by haphut** [comment] 2021-05-05 08:52
Could we collect this into #26? Marking as duplicate for now and closing. If you think these should be separate issues, you can reopen this one.

**Comment by haphut** [comment] 2021-05-05 08:52
Duplicate of #26

**Closed** 2021-05-05 08:52 UTC
Labels: duplicate, frontend, idea

**Comment by pallost** [comment] 2021-05-05 09:03
I was searching for an existing ticket, but somehow couldn't find this one... thanks for resolving!
